<template>
  <div>
    <b-card class="card-co2tips" no-body>
      <b-tabs
        v-model="tabIndex"
        pills
        card
        vertical
        nav-wrapper-class="col-2"
      >
        <b-tab title="How it is calculated?">
          <p>
            <strong class="text-purple">How it is calculated &mdash; CO2 emission factors used and references</strong>
          </p>
          <p class="no-margin">
            <b class="text-purple">Electricity</b>
          </p>
          <p>
            The CO2 emission factor used is <span class="text-underline font-w-400">0.309 kge/kWh</span>, taken from BEIS (2018) <a href="#" class="text-purple" @click.prevent="tabIndex = 1">[1]</a>
          </p>
          <p class="no-margin">
            <b class="text-purple">Gas</b>
          </p>
          <p>
            The CO2 generated by burning natural gas is <span class="text-underline font-w-400">0.185 kg/kWh</span> <a href="#" class="text-purple" @click.prevent="tabIndex = 1">[2]</a>. Average gas infrustructure inefficiencies result in 8.7% of gas losses, and so the CO2 emissions need to be adjusted from 0.185 to <span class="text-underline font-w-400">0.203 kg/kWh</span> <a href="#" class="text-purple" @click.prevent="tabIndex = 1">[3]</a>.
          </p>
        </b-tab>
        <b-tab title="References">
          <p class="no-margin">
            <strong class="text-purple">References:</strong>
          </p>
          <ol class="ml-20">
            <li class="mb-10">BEIS (2018) 2018 Government GHG Conversion Factors for Company Reporting: Methodology paper for emission factors: final report <a href="https://www.gov.uk/government/uploads/system/uploads/attachment_data/file/726911/2018_methodology_paper_FINAL_v01-00.pdf" class="text-purple" target="_blank">(link)</a></li>
            <li class="mb-10">DEFRA (2007) Guidelines to Defra's GHG conversion factors for company reporting <a href="https://www.carbonindependent.org/files/conversion-factors.pdf" class="text-purple" target="_blank">(link)</a></li>
            <li>BERR Energy Trends December 2007 <a href="https://www.carbonindependent.org/files/file43304.pdf" class="text-purple" target="_blank">(link)</a></li>
          </ol>
        </b-tab>
        <b-tab title="Contact us">
          <p>Let us know if you have any comments or questions about Carbon Footprint Calculator &mdash; <a href="mailto:CSR@luxoft.com" class="text-purple">email</a></p>
          <p>We have a Workplace group where you can join our team, contribute to the project, and share your improvement suggestions &mdash; <a href="https://luxoft.workplace.com/groups/549418239645131" class="text-purple">Carbon Footprint Calculator Workplace Group</a></p>
        </b-tab>
        <b-tab title="About" active>
          <p>
            Carbon Footprint Calculator is a <a href="https://luxproject.luxoft.com/confluence/display/CSR" class="text-purple" target="_blank">Luxoft CSR Incubator</a> winner of 2021 &mdash; it is aimed at raising awareness on the environmental issues and demonstrating how individual carbon footprint affects global pollution. Carbon Footprint Calculator is a user-friendly web application accessible for all employees on a voluntary basis in order to track their CO2 emissions and take action on its reduction.
          </p>
          <p>
            Carbon Footprint Calculator provides a rough environmental impact of CO2 emission based on the given responses and is not intended for precise estimation. For a more accurate assessment of carbon footprint and additional information regarding environmental protection please follow the links in the References section.
          </p>
        </b-tab>
      </b-tabs>
    </b-card>
  </div>
</template>

<script>
export default {
  data () {
    return {
      tabIndex: 0
    }
  },
  methods: {
    setTabIndex (index) {
      this.tabIndex = index
    }
  }
}
</script>
