<template>
  <div>
    <section class="carbon-calculator">
      <b-container class="title">
        <b-row>
          <b-col>
            <div class="mb-45" data-aos="fade-up">
              <h1 class="text-center text-uppercase mb-30 mt-30">
                <span>Carbon footprint</span> calculator
              </h1>
            </div>
          </b-col>
        </b-row>

        <div id="main-content">
          <b-card no-body>
            <b-tabs v-model="tabIndex" pills card>
              <!-- start of tab 1 -->
              <b-tab title="Calculator" active>
                <!-- start of intro content -->
                <div v-if="contentPosition === 0">
                  <b-card-text>
                    A carbon footprint is the total amount of greenhouse gases (including carbon dioxide and methane) that are generated by our
                    actions. Luxoft has designed CO2 calculator to demonstrate individual carbon footprint and provide tips to reduce a negative
                    impact on the environment in terms of tons of CO2.
                  </b-card-text>
                  <b-card-text>
                    Lowering individual carbon footprints doesn’t happen overnight!<br>
                    We invite you to excitement journey:
                    <ul class="purple-ul ml-20">
                      <li>Complete the test</li>
                      <li>Find out what is your current carbon footprint</li>
                      <li>Learn tips on how to reduce carbon footprint</li>
                      <li>Take actions</li>
                      <li>
                        Re-take the test in 3-6 months and see the result on how your carbon footprint has changed considering undertaken actions! 
                        We encourage you to share your results at Workplace or with your colleagues
                      </li>
                    </ul>
                  </b-card-text>
                  <div class="text-center mt-20 mb-20">
                    <h5 class="text-purple">
                      How it works
                    </h5>
                  </div>
                  <b-row>
                    <b-col md="3" class="text-center">
                      <b-img src="./static/images/icons/calculator.svg" alt="Calculator" />
                      <p>Calculate your carbon footprint</p>
                    </b-col>
                    <b-col md="1" class="text-center">
                      <b-img src="./static/images/icons/plus.png" alt="Plus" />
                    </b-col>
                    <b-col md="3" class="text-center">
                      <b-img src="./static/images/icons/hands.svg" alt="Hands" />
                      <p>Offset your footprint</p>
                    </b-col>
                    <b-col md="1" class="text-center">
                      <b-img src="./static/images/icons/minus.png" alt="Minus" />
                    </b-col>
                    <b-col md="3" class="text-center">
                      <div>
                        <b-img src="./static/images/icons/tree.svg" alt="Tree" />
                        <p>Solve climate change by saving critical forests</p>
                      </div>
                    </b-col>
                  </b-row>
                  <div class="text-center mb-20">
                    <p>Remember, by making small changes to our actions, we can start making a big difference!</p>
                  </div>
                  <div class="text-center">
                    <div class="button button--purple mt-mb-10 aos-init aos-animate">
                      <a href="#" @click.prevent="contentPosition++">Start</a>
                    </div>
                  </div>
                </div>
                <!-- end of intro content -->

                <div v-if="contentPosition > 0" class="carbon-calculator__tab--content">
                  <b-row class="mb-30">
                    <b-col>
                      <div class="div-flex">
                        <b-img :src="`./static/images/icons/${contentIcon[contentPosition]}`" alt="icon" />
                        <h4 class="title text-uppercase text-purple font-w-700">
                          {{ contentTitle[contentPosition] }}
                        </h4>
                      </div>
                    </b-col>
                    <b-col class="text-right">
                      <a id="tooltip-help" href="#" @click.prevent="goToAbout()">
                        <b-img src="./static/images/icons/info.svg" alt="info" />
                      </a>
                      <b-tooltip target="tooltip-help" triggers="hover">
                        <b>Click to see: how it is calculated?</b>
                      </b-tooltip>
                    </b-col>
                  </b-row>

                  <!-- start of houseHold content -->
                  <div v-if="contentPosition === 1" class="carbon-calculator__tab--content houseHold">
                    <b-row>
                      <b-col>
                        <p>How much electricity is used in your household annually?</p>
                        <div>
                          <label for="range-q1" />
                          <b-form-input
                            id="range-q1"
                            v-model="q1"
                            type="range"
                            :min="min"
                            :max="max"
                            class="range"
                            :style="{backgroundSize: backgroundSizeQ1}"
                            @input="updateRangeQ1"
                          />
                          <ul class="range-ul div-flex">
                            <li>
                              <span>None</span>
                            </li>
                            <li class="text-center">
                              <span>Small house / flat<br>(3,000 kWh)</span>
                            </li>
                            <li class="text-center">
                              <span>Medium<br>(4,800 kWh)</span>
                            </li>
                            <li class="text-center">
                              <span>Large house<br>(7,000 kWh)</span>
                            </li>
                            <li class="text-center">
                              <span>Hall of residence<br>(2,000 kWh)</span>
                            </li>
                          </ul>
                        </div>
                      </b-col>
                    </b-row>

                    <b-row class="mt-20">
                      <b-col>
                        <p>How much gas is used in your household annually?</p>
                        <div>
                          <label for="q2-range" />
                          <b-form-input
                            id="q2-range"
                            v-model="q2"
                            type="range"
                            :min="min"
                            :max="max"
                            class="range"
                            :style="{backgroundSize: backgroundSizeQ2}"
                            @input="updateRangeQ2"
                          />
                          <ul class="range-ul div-flex">
                            <li>
                              <span>None</span>
                            </li>
                            <li class="text-center">
                              <span>Small house / flat<br>(12,000 kWh)</span>
                            </li>
                            <li class="text-center">
                              <span>Medium<br>(18,000 kWh)</span>
                            </li>
                            <li class="text-center">
                              <span>Large house<br>(27,000 kWh)</span>
                            </li>
                            <li class="text-center">
                              <span>Hall of residence<br>(5,000 kWh)</span>
                            </li>
                          </ul>
                        </div>
                      </b-col>
                    </b-row>

                    <b-row class="mt-20">
                      <b-col>
                        <p>Is heating oil, coal, wood or bottled gas used in your household?</p>
                        <b-form-group v-slot="{ ariaDescribedby }">
                          <b-form-radio-group
                            id="oil-radio-group"
                            v-model="showOilNumbers"
                            :aria-describedby="ariaDescribedby"
                          >
                            <b-form-radio :value="false">
                              No
                            </b-form-radio>
                            <b-form-radio :value="true">
                              Yes
                            </b-form-radio>
                          </b-form-radio-group>
                        </b-form-group>
                      </b-col>
                    </b-row>

                    <div v-if="showOilNumbers" class="mt-20">
                      <div>
                        <p>Enter your use over the last year:</p>
                      </div>
                      <b-row class="oil-numbers">
                        <b-col>
                          <div class="oil-numbers__container">
                            <span>The number of litres of <b class="text-purple">heating oil:</b></span>
                            <b-form-input
                              v-model="oil"
                              type="number"
                              :min="min"
                            />
                          </div>
                        </b-col>
                        <b-col>
                          <div class="oil-numbers__container">
                            <span>The number of kilograms of <b class="text-purple">coal:</b></span>
                            <b-form-input
                              v-model="col"
                              type="number"
                              :min="min"
                            />
                          </div>
                        </b-col>
                        <b-col>
                          <div class="oil-numbers__container">
                            <span>The number of kilograms of <b class="text-purple">wood:</b></span>
                            <b-form-input
                              v-model="woo"
                              type="number"
                              :min="min"
                            />
                          </div>
                        </b-col>
                        <b-col>
                          <div class="oil-numbers__container">
                            <span>The number of kilograms of <b class="text-purple">bottled gas:</b></span>
                            <b-form-input
                              v-model="bot"
                              type="number"
                              :min="min"
                            />
                          </div>
                        </b-col>
                      </b-row>
                    </div>
                  </div>
                  <!-- end of houseHold content -->

                  <!-- start of transport content -->
                  <div v-if="contentPosition === 2" class="carbon-calculator__tab--content transport">
                    <b-row>
                      <b-col>
                        <p>
                          What was the approximate usage of <b class="text-purple">buses</b> in the previous year?<br>Enter your regular distance travelled each week or month or whole year:
                        </p>
                        <p class="display-block">
                          Number of kilometers
                        </p>
                        <b-form-input v-model="bus" class="display-block w-60 ml-10" type="number" />
                        <p class="display-block ml-10">
                          per
                        </p>
                        <div class="select-wrapper">
                          <b-form-select v-model="q4" class="select-menu display-block w-100px ml-10" :options="transportOptions" />
                        </div>
                      </b-col>
                    </b-row>
                    <b-row class="mt-25">
                      <b-col>
                        <p>
                          What was the approximate usage of <b class="text-purple">trains</b> in the previous year?<br>Enter your regular distance travelled each week or month or whole year:
                        </p>
                        <p class="display-block">
                          Number of kilometers
                        </p>
                        <b-form-input v-model="train" class="display-block w-60 ml-10" type="number" />
                        <p class="display-block ml-10">
                          per
                        </p>
                        <div class="select-wrapper">
                          <b-form-select v-model="q5" class="display-block w-100px ml-10" :options="transportOptions" />
                        </div>
                      </b-col>
                    </b-row>
                    <b-row class="mt-20">
                      <b-col>
                        <p>
                          How many cars are used by your household?
                        </p>
                        <label for="transport-range" />
                        <b-form-input
                          id="transport-range"
                          v-model="carsNumber"
                          type="range"
                          :min="min"
                          :max="transportMax"
                          class="range"
                          :style="{backgroundSize: backgroundSizeTransport}"
                          @input="updateTransportRange"
                        />
                        <ul class="mt-10 transport-ul div-flex">
                          <li>
                            <span>0</span>
                          </li>
                          <li>
                            <span>1</span>
                          </li>
                          <li>
                            <span>2</span>
                          </li>
                          <li>
                            <span>3</span>
                          </li>
                        </ul>
                      </b-col>
                    </b-row>
                    <div v-if="carsNumber > 0" class="mt-20 transport-cars">
                      <div class="single-car">
                        <b-row>
                          <b-col>
                            <div class="div-flex">
                              <b-img src="./static/images/icons/car.svg" alt="icon" />
                              <h6 class="ml-10 text-purple font-w-700">
                                Car 1
                              </h6>
                            </div>
                          </b-col>
                        </b-row>
                        <b-row class="mt-10">
                          <b-col md="10" lg="8" class="text-left">
                            <p class="display-block">
                              Select car size:
                            </p>
                            <div class="select-wrapper">
                              <b-form-select v-model="car01" class="car-size display-block" :options="carOptions" />
                            </div>
                          </b-col>
                          <b-col v-if="car01 === 'actual'" md="2" lg="2" class="text-left">
                            <b-form-input v-model="mpg01" class="display-block w-60 ml-10" type="number" />
                          </b-col>
                        </b-row>
                        <b-row class="mt-10">
                          <b-col md="10" lg="8" class="text-left">
                            <p class="display-block">
                              Select 12-month car mileage:
                            </p>
                            <div class="select-wrapper">
                              <b-form-select v-model="milage01" class="car-mileage display-block" :options="milageOptions" />
                            </div>
                          </b-col>
                        </b-row>
                      </div>

                      <div v-if="carsNumber > 1" class="single-car mt-10">
                        <b-row>
                          <b-col>
                            <div class="div-flex">
                              <b-img src="./static/images/icons/car.svg" alt="icon" />
                              <h6 class="ml-10 text-purple font-w-700">
                                Car 2
                              </h6>
                            </div>
                          </b-col>
                        </b-row>
                        <b-row class="mt-10">
                          <b-col md="10" lg="8" class="text-left">
                            <p class="display-block">
                              Select car size:
                            </p>
                            <div class="select-wrapper">
                              <b-form-select v-model="car02" class="car-size display-block" :options="carOptions" />
                            </div>
                          </b-col>
                          <b-col v-if="car02 === 'actual'" md="2" lg="2" class="text-left">
                            <b-form-input v-model="mpg02" class="display-block w-60 ml-10" type="number" />
                          </b-col>
                        </b-row>
                        <b-row class="mt-10">
                          <b-col md="10" lg="8" class="text-left">
                            <p class="display-block">
                              Select 12-month car mileage:
                            </p>
                            <div class="select-wrapper">
                              <b-form-select v-model="milage02" class="car-mileage display-block" :options="milageOptions" />
                            </div>
                          </b-col>
                        </b-row>
                      </div>

                      <div v-if="carsNumber > 2" class="single-car mt-10">
                        <b-row>
                          <b-col>
                            <div class="div-flex">
                              <b-img src="./static/images/icons/car.svg" alt="icon" />
                              <h6 class="ml-10 text-purple font-w-700">
                                Car 3
                              </h6>
                            </div>
                          </b-col>
                        </b-row>
                        <b-row class="mt-10">
                          <b-col md="10" lg="8" class="text-left">
                            <p class="display-block">
                              Select car size:
                            </p>
                            <div class="select-wrapper">
                              <b-form-select v-model="car03" class="car-size display-block" :options="carOptions" />
                            </div>
                          </b-col>
                          <b-col v-if="car03 === 'actual'" md="2" lg="2" class="text-left">
                            <b-form-input v-model="mpg03" class="display-block w-60 ml-10" type="number" />
                          </b-col>
                        </b-row>
                        <b-row class="mt-10">
                          <b-col md="10" lg="8" class="text-left">
                            <p class="display-block">
                              Select 12-month car mileage:
                            </p>
                            <div class="select-wrapper">
                              <b-form-select v-model="milage03" class="car-mileage display-block" :options="milageOptions" />
                            </div>
                          </b-col>
                        </b-row>
                      </div>
                    </div>
                  </div>
                  <!-- end of transport content -->

                  <!-- start of lifestyle content -->
                  <div v-if="contentPosition === 3" class="carbon-calculator__tab--content lifestyle">
                    <b-row>
                      <b-col lg="10">
                        <div class="title">
                          <p class="display-block">
                            How much of the food that you eat is organic?
                          </p>
                        </div>
                        <div class="select-wrapper">
                          <b-form-select v-model="q6" class="display-block" :options="foodOptions" />
                        </div>
                      </b-col>
                    </b-row>
                    <b-row>
                      <b-col lg="10">
                        <div class="title">
                          <p class="display-block">
                            How much meat/dairy do you eat personally?
                          </p>
                        </div>
                        <div class="select-wrapper">
                          <b-form-select v-model="q7" class="display-block" :options="meatOptions" />
                        </div>
                      </b-col>
                    </b-row>
                    <b-row>
                      <b-col lg="10">
                        <div class="title">
                          <p class="display-block">
                            How much of your food is produced locally?
                          </p>
                        </div>
                        <div class="select-wrapper">
                          <b-form-select v-model="q8" class="display-block" :options="localOptions" />
                        </div>
                      </b-col>
                    </b-row>
                  </div>
                  <!-- end of lifestyle content -->

                  <!-- start of results content -->
                  <div v-if="contentPosition === 4" class="carbon-calculator__tab--content results">
                    <div class="result-container">
                      <h2 class="text-white">
                        {{ co2Total }}
                      </h2>
                      <p class="text-white">
                        tonnes of CO <sub>2</sub>
                      </p>
                    </div>
                    <b-row class="mt-30">
                      <b-col>
                        <p>
                          The average carbon footprint for a person in the United States is 16 tons, one of the highest rates in the world.
                          Globally, the average is closer to 4 tons. To have the best chance of avoiding a 2°C rise in global temperatures, the
                          average global carbon footprint per year needs to drop under 2 tons by 2050 – this commitment was discussed at
                          <a href="https://www.ipcc.ch/" class="text-purple" target="_blank">IPCC</a> summit.
                        </p>
                      </b-col>
                    </b-row>
                  </div>
                  <!-- end of results content -->

                  <!-- start of nagivation -->
                  <b-row v-if="contentPosition < 4" class="mt-30">
                    <b-col>
                      <div class="text-left">
                        <div class="button t-button mt-mb-10 aos-init aos-animate">
                          <a href="#" @click.prevent="contentPosition--">Back</a>
                        </div>
                      </div>
                    </b-col>
                    <b-col class="text-center">
                      <ul class="dots-ul mt-20">
                        <li :class="contentPosition === 1 ? 'active' : '' " />
                        <li :class="contentPosition === 2 ? 'active' : '' " />
                        <li :class="contentPosition === 3 ? 'active' : '' " />
                      </ul>
                    </b-col>
                    <b-col>
                      <div class="text-right">
                        <div class="button button--purple mt-mb-10 aos-init aos-animate">
                          <a href="#" @click.prevent="contentPosition++">{{ contentPosition > 2 ? 'Results' : 'Next' }}</a>
                        </div>
                      </div>
                    </b-col>
                  </b-row>
                  <b-row v-if="contentPosition === 4">
                    <b-col class="mt-20">
                      <div class="text-center">
                        <div class="button t-button mt-mb-10 aos-init aos-animate">
                          <a href="#" @click.prevent="contentPosition--">Back</a>
                        </div>
                      </div>
                    </b-col>
                  </b-row>
                  <!-- end of nagivation -->
                </div>
              </b-tab>
              <!-- end of tab 1 -->
              <b-tab title="CO2 tips">
                <Co2tips />
              </b-tab>
              <b-tab title="About">
                <About ref="aboutComponent" />
              </b-tab>
            </b-tabs>
          </b-card>
        </div>

        <footer class="footer">
          <b-row>
            <b-col>
              <p>© {{ year }} LUXOFT. ALL RIGHTS RESERVED.</p>
            </b-col>
            <b-col class="text-right">
              <b-img src="./static/images/icons/luxoft-new-purple.svg" class="logo" alt="logo" />
            </b-col>
          </b-row>
        </footer>
      </b-container>
    </section>
  </div>
</template>

<script>

import Co2tips from './Co2tips.vue'
import About from './About.vue'

export default {
  components: { Co2tips, About },
  data () {
    return {
      min: 0,
      max: 4,
      transportMax: 3,
      contentTitle: ['intro', 'HOUSEHOLD', 'TRANSPORT', 'LIFESTYLE', 'RESULTS'],
      contentIcon: ['intro', 'household.svg', 'transport.svg', 'lifestyle.svg', 'calculator.svg'],
      contentPosition: 0,
      year: null,
      tabIndex: 0,
      q1: 0,
      q2: 0,
      q4: 'year',
      q5: 'year',
      q6: 'none',
      q7: 'average',
      q8: 'average',
      bus: 0,
      train: 0,
      backgroundSizeQ1: '0% 100%',
      backgroundSizeQ2: '0% 100%',
      backgroundSizeTransport: '0% 100%',
      showOilNumbers: false,
      oil: 0,
      col: 0,
      woo: 0,
      bot: 0,
      transportOptions: [
        { value: 'year', text: 'year' },
        { value: 'month', text: 'month' },
        { value: 'week', text: 'week' }
      ],
      carOptions: [
        { value: 'sports', text: 'Sports car or large SUV (35 mpg)' },
        { value: 'small', text: 'Small or medium SUV, or MPV (46 mpg)' },
        { value: 'city', text: 'City, small, medium, large or estate car (52 mpg)' },
        { value: 'actual', text: 'Enter actual mpg:' }
      ],
      milageOptions: [
        { value: 'low', text: 'Low (6,000 miles)' },
        { value: 'average', text: 'Average (9,000 miles)' },
        { value: 'high', text: 'High (12,000 miles)' },
        { value: 'actual', text: 'Enter actual milage:' }
      ],
      car01: 'sports',
      car02: 'sports',
      car03: 'sports',
      milage01: 'low',
      milage02: 'low',
      milage03: 'low',
      mpg01: 0,
      mpg02: 0,
      mpg03: 0,
      foodOptions: [
        { value: 'none', text: 'None' },
        { value: 'some', text: 'Some' },
        { value: 'most', text: 'Most' },
        { value: 'all', text: 'All' }
      ],
      meatOptions: [
        { value: 'average', text: 'Average meat/dairy' },
        { value: 'below', text: 'Below-average meat/dairy' },
        { value: 'above', text: 'Above-average meat/dairy' },
        { value: 'lacto', text: 'Lacto-vegetarian' },
        { value: 'vegan', text: 'Vegan' }
      ],
      localOptions: [
        { value: 'average', text: 'Average' },
        { value: 'below', text: 'Very little' },
        { value: 'above', text: 'Above average' },
        { value: 'all', text: 'Almost all' }
      ],
      carsNumber: 0,
      co2Total: 0
    }
  },
  watch: {
    tabIndex: function (oldVal, newVal) {
      if (
        (oldVal === 0 && newVal === 1) ||
        (oldVal === 0 && newVal === 2)
      ) {
        this.contentPosition = 0
      }
    },
    contentPosition: function (oldVal, newVal) {
      if (oldVal === 4 && newVal === 3) {
        this.calculateResult()
      }
    }
  },
  created () {
    this.year = new Date().getFullYear()
  },
  mounted () {
  },
  methods: {
    goToAbout () {
      this.tabIndex = 2
      this.$refs.aboutComponent.setTabIndex(0)
    },
    roundToTwo (num) {
      return +(Math.round(num + 'e+2') + 'e-2')
    },
    calculateResult () {
      const vm = this
      vm.co2Total = 0
      const eleCoef = 0.309

      if (parseInt(vm.q1) === 0) {
        vm.co2Total = vm.co2Total + 0
      } else if (parseInt(vm.q1) === 1) {
        vm.co2Total = vm.co2Total + 3000 * eleCoef / 1000
      } else if (parseInt(vm.q1) === 2) {
        vm.co2Total = vm.co2Total + 4800 * eleCoef / 1000
      } else if (parseInt(vm.q1) === 3) {
        vm.co2Total = vm.co2Total + 7000 * eleCoef / 1000
      } else if (parseInt(vm.q1) === 4) {
        vm.co2Total = vm.co2Total + 2000 * eleCoef / 1000
      }

      const gasCoef = 0.203
      if (parseInt(vm.q2) === 0) {
        vm.co2Total = vm.co2Total + 0
      } else if (parseInt(vm.q2) === 1) {
        vm.co2Total = vm.co2Total + 12000 * gasCoef / 1000
      } else if (parseInt(vm.q2) === 2) {
        vm.co2Total = vm.co2Total + 18000 * gasCoef / 1000
      } else if (parseInt(vm.q2) === 3) {
        vm.co2Total = vm.co2Total + 27000 * gasCoef / 1000
      } else if (parseInt(vm.q2) === 4) {
        vm.co2Total = vm.co2Total + 5000 * gasCoef / 1000
      }

      const oilCoed = 2.96
      const coalCoef = 3.26
      const woodCoef = 0.1
      const borCoef = 3.68

      if (parseInt(vm.oil) === 0) {
        vm.co2Total = vm.co2Total + 0
      } else { vm.co2Total = vm.co2Total + parseInt(vm.oil) * oilCoed / 1000 }

      if (parseInt(vm.col) === 0) {
        vm.co2Total = vm.co2Total + 0
      } else { vm.co2Total = vm.co2Total + parseInt(vm.col) * coalCoef / 1000 }

      if (parseInt(vm.woo) === 0) {
        vm.co2Total = vm.co2Total + 0
      } else { vm.co2Total = vm.co2Total + parseInt(vm.woo) * woodCoef / 1000 }

      if (parseInt(vm.bot) === 0) {
        vm.co2Total = vm.co2Total + 0
      } else { vm.co2Total = vm.co2Total + parseInt(vm.bot) * borCoef / 1000 }

      if (isNaN(vm.bus) || parseInt(vm.bus) === 0) {
        vm.co2Total = vm.co2Total + 0
      } else {
        if (vm.q4 === 'week') {
          vm.co2Total = vm.co2Total + parseInt(vm.bus) * 48 * 102.27 / 1000000
        } else if (vm.q4 === 'month') {
          vm.co2Total = vm.co2Total + parseInt(vm.bus) * 12 * 102.27 / 1000000
        } else if (vm.q4 === 'year') { vm.co2Total = vm.co2Total + parseInt(vm.bus) * 1 * 102.27 / 1000000 }
      }

      if (isNaN(vm.train) || parseInt(vm.train) === 0) {
        vm.co2Total = vm.co2Total + 0
      } else {
        if (vm.q5 === 'week') {
          vm.co2Total = vm.co2Total + parseInt(vm.train) * 48 * 35.49 / 1000000
        } else if (vm.q5 === 'month') {
          vm.co2Total = vm.co2Total + parseInt(vm.train) * 12 * 35.49 / 1000000
        } else if (vm.q5 === 'year') { vm.co2Total = vm.co2Total + parseInt(vm.train) * 1 * 35.49 / 1000000 }
      }

      if (vm.q6 === 'none') {
        vm.co2Total = vm.co2Total + 0.7
      } else if (vm.q6 === 'some') {
        vm.co2Total = vm.co2Total + 0.5
      } else if (vm.q6 === 'most') {
        vm.co2Total = vm.co2Total + 0.2
      } else if (vm.q6 === 'all') { vm.co2Total = vm.co2Total + 0 }

      if (vm.q7 === 'average') {
        vm.co2Total = vm.co2Total + 0.4
      } else if (vm.q7 === 'below') {
        vm.co2Total = vm.co2Total + 0.25
      } else if (vm.q7 === 'above') {
        vm.co2Total = vm.co2Total + 0.6
      } else if (vm.q7 === 'lacto') {
        vm.co2Total = vm.co2Total + 0.1
      } else if (vm.q7 === 'vegan') { vm.co2Total = vm.co2Total + 0 }

      if (vm.q8 === 'average') {
        vm.co2Total = vm.co2Total + 0.3
      } else if (vm.q8 === 'below') {
        vm.co2Total = vm.co2Total + 0.5
      } else if (vm.q8 === 'above') {
        vm.co2Total = vm.co2Total + 0.2
      } else if (vm.q8 === 'all') { vm.co2Total = vm.co2Total + 0.1 }

      vm.co2Total = vm.roundToTwo(vm.co2Total)
      // eslint-disable-next-line no-undef
      appInsights.trackEvent({ name: 'CO2 tonnes', properties: { co2_tonnes: vm.co2Total } })
    },
    updateRangeQ1 () {
      this.backgroundSizeQ1 = (this.q1 - this.min) * 100 / (this.max - this.min) + '% 100%'
    },
    updateRangeQ2 () {
      this.backgroundSizeQ2 = (this.q2 - this.min) * 100 / (this.max - this.min) + '% 100%'
    },
    updateTransportRange () {
      this.backgroundSizeTransport = (this.carsNumber - this.min) * 100 / (this.transportMax - this.min) + '% 100%'
    }
  }
}
</script>
